version: 2

models:
  - name: stg_telegram_messages
    description: Cleaned and standardized staging table for Telegram messages.
    columns:
      - name: message_id
        description: Unique identifier for the message from Telegram.
        tests:
          - unique
          - not_null
      - name: message_timestamp
        description: Timestamp when the message was posted.
        tests:
          - not_null
      - name: channel_id
        description: Unique identifier for the Telegram channel.
        tests:
          - not_null
      - name: message_text
        description: The content of the message.
      - name: views_count
        description: Number of views the message received.
      - name: has_media
        description: Boolean indicating if the message contains any media.

  - name: dim_channels
    description: Dimension table containing information about Telegram channels.
    columns:
      - name: channel_id
        description: Primary key for the channel dimension table (Telegram channel ID).
        tests:
          - unique
          - not_null
      - name: channel_username
        description: Telegram username of the channel.
      - name: channel_title
        description: Display title of the Telegram channel.

  - name: dim_dates
    description: Standard date dimension table.
    columns:
      - name: date_day
        description: The actual date.
        tests:
          - unique
          - not_null
      - name: date_key
        description: Integer representation of the date (YYYYMMDD).
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: Fact table containing key metrics for each Telegram message.
    columns:
      - name: message_pk
        description: Primary key for the fact messages table (composite of message_id and channel_id).
        tests:
          - unique
          - not_null
      - name: message_id
        description: Original Telegram message ID.
        tests:
          - not_null
      - name: channel_id
        description: Foreign key to dim_channels.
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_id
      - name: date_key
        description: Foreign key to dim_dates.
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: message_length
        description: Length of the message text in characters.
        tests:
          - positive_value # Custom test