version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: raw_yolo_detections
        description: Raw object detection results from YOLOv8 model on Telegram images.
        columns:
          - name: message_id
            description: Original Telegram message ID associated with the image.
            tests:
              - not_null
          - name: detected_object_class
            description: Class of the object detected by YOLO (e.g., 'person', 'car', 'pill').
            tests:
              - not_null
          - name: confidence_score
            description: Confidence score of the detection (0-1).
            tests:
              - not_null
              - dbt_utils.not_negative
              - dbt_utils.at_least_one

models:

  - name: stg_yolo_detections
    description: Cleaned and standardized staging table for YOLO object detections.
    columns:
      - name: image_detection_pk
        description: Primary key for the image detection staging table.
        tests:
          - unique
          - not_null
      - name: message_id
        description: Original Telegram message ID associated with the image.
        tests:
          - not_null
      - name: detected_object_class
        description: Class of the object detected by YOLO.
        tests:
          - not_null
      - name: confidence_score
        description: Confidence score of the detection.
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0.0
              max_value: 1.0

  - name: fct_image_detections
    description: Fact table containing detailed information about objects detected in Telegram images.
    columns:
      - name: image_detection_pk
        description: Primary key for the image detections fact table.
        tests:
          - unique
          - not_null
      - name: message_id
        description: Original Telegram message ID.
        tests:
          - not_null
      - name: message_pk
        description: Foreign key to the fct_messages table.
        tests:
          - not_null
          - relationships:
              to: ref('fct_messages')
              field: message_pk
      - name: detected_object_class
        description: Class of the object detected (e.g., 'pill', 'cream', 'syringe').
        tests:
          - not_null
      - name: confidence_score
        description: Confidence score of the detection.
        tests:
          - not_null